#!/usr/bin/env bash

# Generate DDEV Vite proxy files that are local to this checkout. DDEV derives
# the same project name from the checkout directory after the tracked `name:`
# entry was removed from .ddev/config.yaml.
set -euo pipefail

project_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
project_name=$(basename "$project_root" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')
project_name=${project_name#-}
project_name=${project_name%-}

if [[ -z "$project_name" ]]; then
    echo "Cannot derive a DDEV project name from $project_root." >&2
    exit 1
fi

cd "$project_root"
# Detect whether this project uses Vite (e.g. vite.config.*, package.json with vite, or praetorius/vite-asset-collector)
uses_vite=false
for f in vite.config.js vite.config.ts vite.config.mjs vite.config.cjs; do
    if [[ -f "$f" ]]; then
        uses_vite=true
        break
    fi
done

if [[ "$uses_vite" = false && -f "composer.json" ]]; then
    if grep -q '"praetorius/vite-asset-collector"' composer.json; then
        uses_vite=true
    fi
fi

if [[ "$uses_vite" = false && -f "package.json" ]]; then
    if grep -q '"vite"' package.json; then
        uses_vite=true
    fi
fi

if [[ "$uses_vite" = true ]]; then
    echo "Configuring Vite proxy for DDEV project: $project_name"
    mkdir -p .ddev/apache .ddev/nginx_full

    cat > .ddev/config.vite.yaml <<EOF
# Generated by scripts/bootstrap-ddev-worktree.sh; do not commit.
additional_hostnames:
  - vite.${project_name}
web_environment:
  - VITE_SERVER_URI=https://vite.${project_name}.ddev.site
  - VITE_PACKAGE_MANAGER=npm
EOF

    cat > .ddev/apache/vite.conf <<EOF
# Generated by scripts/bootstrap-ddev-worktree.sh; do not commit.
<VirtualHost *:80>
    ServerName vite.${project_name}.ddev.site
    ServerAlias vite.*
    DocumentRoot /var/www/html/.ddev/vite/
    ErrorDocument 503 "/vite-server-not-running.html"

    ProxyPreserveHost On
    ProxyPass / http://localhost:5173/ upgrade=websocket
    ProxyPassReverse / http://localhost:5173/

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:5173/\$1" [P,L]

    <Location "/vite-server-not-running.html">
        ProxyPass !
    </Location>

    <Directory "/var/www/html/.ddev/vite/">
        Require all granted
    </Directory>
    <Directory "/mnt/ddev_config/vite/">
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog \${APACHE_LOG_DIR}/access.log combined
    Alias "/phpstatus" "/var/www/phpstatus.php"
</VirtualHost>
EOF

    cat > .ddev/nginx_full/vite.conf <<EOF
# Generated by scripts/bootstrap-ddev-worktree.sh; do not commit.
server {
    server_name vite.${project_name}.ddev.site;

    listen 80;
    listen 443 ssl;

    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;
    include /etc/nginx/monitoring.conf;
    sendfile off;
    error_log /dev/stdout info;
    access_log off;

    location /vite-server-not-running.html {
        root /mnt/ddev_config/vite/;
    }

    location / {
        proxy_pass http://localhost:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Host \$http_x_forwarded_host;
        error_page 502 /vite-server-not-running.html;
    }
}
EOF
else
    echo "No Vite configuration detected (project uses standard TYPO3 assets, e.g. bootstrap-package or plain CSS)."
    echo "Skipping Vite proxy setup."
    rm -f .ddev/config.vite.yaml .ddev/apache/vite.conf .ddev/nginx_full/vite.conf
fi

# Clean up stale Traefik config and certificate overrides that do not belong to this project
if [[ -d .ddev/traefik/config ]]; then
    for f in .ddev/traefik/config/*.yaml; do
        [[ -f "$f" ]] || continue
        base=$(basename "$f" .yaml)
        if [[ "$base" != "$project_name" ]]; then
            echo "Removing stale Traefik config: $f"
            rm -f "$f"
        fi
    done
fi

if [[ -d .ddev/traefik/certs ]]; then
    for f in .ddev/traefik/certs/*; do
        [[ -f "$f" ]] || continue
        base=$(basename "$f")
        if [[ "$base" != "${project_name}.crt" && "$base" != "${project_name}.key" ]]; then
            echo "Removing stale Traefik cert/key: $f"
            rm -f "$f"
        fi
    done
fi

echo "Generated Vite configuration for DDEV project: $project_name"
